name: CI

on: [push]

jobs:
  build:
    runs-on: testrunner

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, self-hosted runner!
      - name: Run a multi-line script
        run: |
          echo This script runs on your self-hosted runner.
          echo Add other necessary steps here.
